import en from "./locales/en.json";
import bn from "./locales/bn.json";
import hi from "./locales/hi.json";
import mr from "./locales/mr.json";
import ta from "./locales/ta.json";
import te from "./locales/te.json";
import kn from "./locales/kn.json";
import ml from "./locales/ml.json";
import gu from "./locales/gu.json";
import pa from "./locales/pa.json";
import or from "./locales/or.json";
import as from "./locales/as.json";
import bho from "./locales/bho.json";
import mai from "./locales/mai.json";
import ur from "./locales/ur.json";
import { getLanguageConfig } from "./languageConfig";

const locales: Record<string, typeof en> = { en, bn, hi, mr, ta, te, kn, ml, gu, pa, or, as, bho, mai, ur };

const uiLabels: Record<string, Record<string, string>> = {
  en: { profileSubtitle: "A living profile that grows as WorkSpot learns about your work and progress.", opportunitiesSubtitle: "Based on your skills, experience, location and goals.", advisorSubtitle: "Ask anything about your work, training, opportunities, or support.", progressSubtitle: "See what you have completed and where your next opportunity can take you.", notificationsSubtitle: "Useful reminders and updates from your WorkSpot journey.", helpSubtitle: "Choose the kind of support that feels easiest right now.", updateWithAI: "Update with AI", searchOpportunities: "Search opportunities", whyFits: "Why this fits you", viewDetails: "View Details", askWorkSpotAI: "Ask WorkSpot AI", voiceMode: "Voice mode", quickQuestions: "Quick questions", whatHelp: "What can I help with?", markAllRead: "Mark all read", recordAgain: "Record Again", typeInstead: "Type instead", previewLabel: "WORKSPOT AI · PREVIEW", play: "Play recording", pause: "Pause recording" },
  bn: { profileSubtitle: "WorkSpot আপনার কাজ ও অগ্রগতি বুঝে বেড়ে ওঠা একটি জীবন্ত প্রোফাইল।", opportunitiesSubtitle: "আপনার দক্ষতা, অভিজ্ঞতা, অবস্থান ও লক্ষ্য অনুযায়ী।", advisorSubtitle: "আপনার কাজ, প্রশিক্ষণ, সুযোগ বা সহায়তা সম্পর্কে যেকোনো প্রশ্ন করুন।", progressSubtitle: "আপনি কী সম্পন্ন করেছেন এবং পরের সুযোগ আপনাকে কোথায় নিয়ে যেতে পারে তা দেখুন।", notificationsSubtitle: "আপনার WorkSpot যাত্রার দরকারি অনুস্মারক ও আপডেট।", helpSubtitle: "এই মুহূর্তে যে সহায়তাটি আপনার জন্য সহজ মনে হয় তা বেছে নিন।", updateWithAI: "AI দিয়ে আপডেট করুন", searchOpportunities: "সুযোগ খুঁজুন", whyFits: "কেন এটি আপনার জন্য উপযুক্ত", viewDetails: "বিস্তারিত দেখুন", askWorkSpotAI: "WorkSpot AI-কে জিজ্ঞাসা করুন", voiceMode: "ভয়েস মোড", quickQuestions: "দ্রুত প্রশ্ন", whatHelp: "আমি কীভাবে সাহায্য করতে পারি?", markAllRead: "সব পড়া হিসেবে চিহ্নিত করুন", recordAgain: "আবার রেকর্ড করুন", typeInstead: "এর বদলে লিখুন", previewLabel: "WORKSPOT AI · প্রিভিউ", play: "রেকর্ডিং চালান", pause: "রেকর্ডিং থামান" },
  hi: { profileSubtitle: "एक जीवंत प्रोफ़ाइल जो WorkSpot के आपके काम और प्रगति को समझने के साथ बढ़ती है।", opportunitiesSubtitle: "आपके कौशल, अनुभव, स्थान और लक्ष्यों के आधार पर।", advisorSubtitle: "अपने काम, प्रशिक्षण, अवसर या सहायता के बारे में कुछ भी पूछें।", progressSubtitle: "देखें आपने क्या पूरा किया है और अगला अवसर आपको कहां ले जा सकता है।", notificationsSubtitle: "आपकी WorkSpot यात्रा के उपयोगी रिमाइंडर और अपडेट।", helpSubtitle: "अभी जो सहायता आसान लगे उसे चुनें।", updateWithAI: "AI से अपडेट करें", searchOpportunities: "अवसर खोजें", whyFits: "यह आपके लिए क्यों उपयुक्त है", viewDetails: "विवरण देखें", askWorkSpotAI: "WorkSpot AI से पूछें", voiceMode: "वॉइस मोड", quickQuestions: "त्वरित प्रश्न", whatHelp: "मैं कैसे मदद कर सकता हूं?", markAllRead: "सभी को पढ़ा हुआ करें", recordAgain: "फिर रिकॉर्ड करें", typeInstead: "इसके बजाय लिखें", previewLabel: "WORKSPOT AI · प्रीव्यू", play: "रिकॉर्डिंग चलाएं", pause: "रिकॉर्डिंग रोकें" },
  mr: { profileSubtitle: "WorkSpot तुमच्या कामाबद्दल आणि प्रगतीबद्दल शिकत असताना वाढणारे जिवंत प्रोफाइल.", opportunitiesSubtitle: "तुमची कौशल्ये, अनुभव, स्थान आणि उद्दिष्टांवर आधारित.", advisorSubtitle: "तुमचे काम, प्रशिक्षण, संधी किंवा मदतीबद्दल काहीही विचारा.", progressSubtitle: "तुम्ही काय पूर्ण केले आणि पुढची संधी कुठे घेऊन जाऊ शकते ते पहा.", notificationsSubtitle: "तुमच्या WorkSpot प्रवासातील उपयुक्त आठवणी आणि अपडेट्स.", helpSubtitle: "आत्ता सोपी वाटणारी मदत निवडा.", updateWithAI: "AI ने अपडेट करा", searchOpportunities: "संधी शोधा", whyFits: "हे तुमच्यासाठी का योग्य आहे", viewDetails: "तपशील पहा", askWorkSpotAI: "WorkSpot AI ला विचारा", voiceMode: "व्हॉइस मोड", quickQuestions: "जलद प्रश्न", whatHelp: "मी कशी मदत करू?", markAllRead: "सर्व वाचले म्हणून चिन्हांकित करा", recordAgain: "पुन्हा रेकॉर्ड करा", typeInstead: "त्याऐवजी लिहा", previewLabel: "WORKSPOT AI · पूर्वावलोकन", play: "रेकॉर्डिंग चालवा", pause: "रेकॉर्डिंग थांबवा" },
  ta: { profileSubtitle: "WorkSpot உங்கள் வேலை மற்றும் முன்னேற்றத்தை அறிந்துகொள்ளும் போது வளர்கின்ற உயிருள்ள சுயவிவரம்.", opportunitiesSubtitle: "உங்கள் திறன்கள், அனுபவம், இடம் மற்றும் இலக்குகளின் அடிப்படையில்.", advisorSubtitle: "உங்கள் வேலை, பயிற்சி, வாய்ப்புகள் அல்லது உதவி பற்றி எதையும் கேளுங்கள்.", progressSubtitle: "நீங்கள் முடித்தவற்றையும் அடுத்த வாய்ப்பு உங்களை எங்கு அழைத்துச் செல்லும் என்பதையும் பாருங்கள்.", notificationsSubtitle: "உங்கள் WorkSpot பயணத்தின் பயனுள்ள நினைவூட்டல்கள் மற்றும் புதுப்பிப்புகள்.", helpSubtitle: "இப்போது எளிதாக இருக்கும் உதவியைத் தேர்ந்தெடுக்கவும்.", updateWithAI: "AI மூலம் புதுப்பிக்கவும்", searchOpportunities: "வாய்ப்புகளைத் தேடுங்கள்", whyFits: "இது உங்களுக்கு ஏன் பொருந்துகிறது", viewDetails: "விவரங்களைப் பார்க்கவும்", askWorkSpotAI: "WorkSpot AI-யிடம் கேளுங்கள்", voiceMode: "குரல் பயன்முறை", quickQuestions: "விரைவு கேள்விகள்", whatHelp: "நான் எப்படி உதவலாம்?", markAllRead: "அனைத்தையும் படித்ததாகக் குறிக்கவும்", recordAgain: "மீண்டும் பதிவு செய்யவும்", typeInstead: "அதற்கு பதிலாக தட்டச்சு செய்யவும்", previewLabel: "WORKSPOT AI · முன்னோட்டம்", play: "பதிவை இயக்கவும்", pause: "பதிவை இடைநிறுத்தவும்" },
  te: { profileSubtitle: "WorkSpot మీ పని మరియు పురోగతిని తెలుసుకునే కొద్దీ ఎదిగే జీవంతమైన ప్రొఫైల్.", opportunitiesSubtitle: "మీ నైపుణ్యాలు, అనుభవం, ప్రాంతం మరియు లక్ష్యాల ఆధారంగా.", advisorSubtitle: "మీ పని, శిక్షణ, అవకాశాలు లేదా సహాయం గురించి ఏదైనా అడగండి.", progressSubtitle: "మీరు పూర్తి చేసినవి, తదుపరి అవకాశం మిమ్మల్ని ఎక్కడికి తీసుకెళ్తుందో చూడండి.", notificationsSubtitle: "మీ WorkSpot ప్రయాణానికి ఉపయోగకరమైన రిమైండర్లు మరియు నవీకరణలు.", helpSubtitle: "ఇప్పుడు సులభంగా అనిపించే సహాయాన్ని ఎంచుకోండి.", updateWithAI: "AIతో నవీకరించండి", searchOpportunities: "అవకాశాలను వెతకండి", whyFits: "ఇది మీకు ఎందుకు సరిపోతుంది", viewDetails: "వివరాలను చూడండి", askWorkSpotAI: "WorkSpot AIని అడగండి", voiceMode: "వాయిస్ మోడ్", quickQuestions: "త్వరిత ప్రశ్నలు", whatHelp: "నేను ఎలా సహాయం చేయగలను?", markAllRead: "అన్నింటినీ చదివినవిగా గుర్తించండి", recordAgain: "మళ్లీ రికార్డ్ చేయండి", typeInstead: "బదులుగా టైప్ చేయండి", previewLabel: "WORKSPOT AI · ప్రివ్యూ", play: "రికార్డింగ్ ప్లే చేయండి", pause: "రికార్డింగ్ ఆపండి" },
  kn: { profileSubtitle: "WorkSpot ನಿಮ್ಮ ಕೆಲಸ ಮತ್ತು ಪ್ರಗತಿಯನ್ನು ತಿಳಿದುಕೊಳ್ಳುತ್ತಾ ಬೆಳೆಯುವ ಜೀವಂತ ಪ್ರೊಫೈಲ್.", opportunitiesSubtitle: "ನಿಮ್ಮ ಕೌಶಲ್ಯ, ಅನುಭವ, ಸ್ಥಳ ಮತ್ತು ಗುರಿಗಳ ಆಧಾರದ ಮೇಲೆ.", advisorSubtitle: "ನಿಮ್ಮ ಕೆಲಸ, ತರಬೇತಿ, ಅವಕಾಶಗಳು ಅಥವಾ ಸಹಾಯದ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ.", progressSubtitle: "ನೀವು ಪೂರ್ಣಗೊಳಿಸಿದುದನ್ನು ಮತ್ತು ಮುಂದಿನ ಅವಕಾಶ ಎಲ್ಲಿಗೆ ಕರೆದೊಯ್ಯಬಹುದು ಎಂಬುದನ್ನು ನೋಡಿ.", notificationsSubtitle: "ನಿಮ್ಮ WorkSpot ಪ್ರಯಾಣದ ಉಪಯುಕ್ತ ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ನವೀಕರಣಗಳು.", helpSubtitle: "ಈಗ ಸುಲಭವೆನಿಸುವ ಸಹಾಯವನ್ನು ಆರಿಸಿ.", updateWithAI: "AI ಮೂಲಕ ನವೀಕರಿಸಿ", searchOpportunities: "ಅವಕಾಶಗಳನ್ನು ಹುಡುಕಿ", whyFits: "ಇದು ನಿಮಗೆ ಏಕೆ ಸೂಕ್ತವಾಗಿದೆ", viewDetails: "ವಿವರಗಳನ್ನು ನೋಡಿ", askWorkSpotAI: "WorkSpot AI ಅನ್ನು ಕೇಳಿ", voiceMode: "ಧ್ವನಿ ಮೋಡ್", quickQuestions: "ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು", whatHelp: "ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?", markAllRead: "ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ", recordAgain: "ಮತ್ತೆ ರೆಕಾರ್ಡ್ ಮಾಡಿ", typeInstead: "ಬದಲಿಗೆ ಟೈಪ್ ಮಾಡಿ", previewLabel: "WORKSPOT AI · ಪೂರ್ವವೀಕ್ಷಣೆ", play: "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ಲೇ ಮಾಡಿ", pause: "ರೆಕಾರ್ಡಿಂಗ್ ವಿರಾಮಗೊಳಿಸಿ" },
  ml: { profileSubtitle: "WorkSpot നിങ്ങളുടെ ജോലിയും പുരോഗതിയും മനസ്സിലാക്കുന്നതിനനുസരിച്ച് വളരുന്ന ജീവിക്കുന്ന പ്രൊഫൈൽ.", opportunitiesSubtitle: "നിങ്ങളുടെ കഴിവുകൾ, അനുഭവം, സ്ഥലം, ലക്ഷ്യങ്ങൾ എന്നിവയെ അടിസ്ഥാനമാക്കി.", advisorSubtitle: "നിങ്ങളുടെ ജോലി, പരിശീലനം, അവസരങ്ങൾ അല്ലെങ്കിൽ സഹായം എന്നിവയെക്കുറിച്ച് എന്തും ചോദിക്കൂ.", progressSubtitle: "നിങ്ങൾ പൂർത്തിയാക്കിയതും അടുത്ത അവസരം നിങ്ങളെ എവിടേക്ക് നയിക്കുമെന്നും കാണുക.", notificationsSubtitle: "നിങ്ങളുടെ WorkSpot യാത്രയിലെ ഉപയോഗപ്രദമായ ഓർമ്മപ്പെടുത്തലുകളും അപ്‌ഡേറ്റുകളും.", helpSubtitle: "ഇപ്പോൾ എളുപ്പമെന്ന് തോന്നുന്ന സഹായം തിരഞ്ഞെടുക്കുക.", updateWithAI: "AI ഉപയോഗിച്ച് അപ്‌ഡേറ്റ് ചെയ്യുക", searchOpportunities: "അവസരങ്ങൾ തിരയുക", whyFits: "ഇത് നിങ്ങൾക്ക് എന്തുകൊണ്ട് അനുയോജ്യം", viewDetails: "വിശദാംശങ്ങൾ കാണുക", askWorkSpotAI: "WorkSpot AI-യോട് ചോദിക്കുക", voiceMode: "വോയ്സ് മോഡ്", quickQuestions: "ദ്രുത ചോദ്യങ്ങൾ", whatHelp: "എനിക്ക് എങ്ങനെ സഹായിക്കാം?", markAllRead: "എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക", recordAgain: "വീണ്ടും റെക്കോർഡ് ചെയ്യുക", typeInstead: "പകരം ടൈപ്പ് ചെയ്യുക", previewLabel: "WORKSPOT AI · പ്രിവ്യൂ", play: "റെക്കോർഡിംഗ് പ്ലേ ചെയ്യുക", pause: "റെക്കോർഡിംഗ് നിർത്തുക" },
  gu: { profileSubtitle: "WorkSpot તમારા કામ અને પ્રગતિને સમજતાં વધતું જીવંત પ્રોફાઇલ.", opportunitiesSubtitle: "તમારી કુશળતા, અનુભવ, સ્થાન અને લક્ષ્યોના આધારે.", advisorSubtitle: "તમારા કામ, તાલીમ, તકો અથવા મદદ વિશે કંઈપણ પૂછો.", progressSubtitle: "તમે શું પૂર્ણ કર્યું છે અને આગળની તક તમને ક્યાં લઈ જઈ શકે છે તે જુઓ.", notificationsSubtitle: "તમારી WorkSpot યાત્રાના ઉપયોગી રિમાઇન્ડર અને અપડેટ્સ.", helpSubtitle: "હમણાં સરળ લાગે તેવી મદદ પસંદ કરો.", updateWithAI: "AI વડે અપડેટ કરો", searchOpportunities: "તકો શોધો", whyFits: "આ તમારા માટે કેમ યોગ્ય છે", viewDetails: "વિગતો જુઓ", askWorkSpotAI: "WorkSpot AI ને પૂછો", voiceMode: "વૉઇસ મોડ", quickQuestions: "ઝડપી પ્રશ્નો", whatHelp: "હું કેવી રીતે મદદ કરી શકું?", markAllRead: "બધાને વાંચેલા તરીકે ચિહ્નિત કરો", recordAgain: "ફરી રેકોર્ડ કરો", typeInstead: "તેના બદલે ટાઇપ કરો", previewLabel: "WORKSPOT AI · પૂર્વાવલોકન", play: "રેકોર્ડિંગ ચલાવો", pause: "રેકોર્ડિંગ થોભાવો" },
  pa: { profileSubtitle: "WorkSpot ਤੁਹਾਡੇ ਕੰਮ ਅਤੇ ਤਰੱਕੀ ਨੂੰ ਸਮਝਦਿਆਂ ਵਧਦੀ ਜੀਵੰਤ ਪ੍ਰੋਫਾਈਲ ਹੈ।", opportunitiesSubtitle: "ਤੁਹਾਡੇ ਹੁਨਰ, ਤਜਰਬੇ, ਥਾਂ ਅਤੇ ਟੀਚਿਆਂ ਦੇ ਆਧਾਰ ਤੇ।", advisorSubtitle: "ਆਪਣੇ ਕੰਮ, ਸਿਖਲਾਈ, ਮੌਕਿਆਂ ਜਾਂ ਮਦਦ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ।", progressSubtitle: "ਦੇਖੋ ਤੁਸੀਂ ਕੀ ਪੂਰਾ ਕੀਤਾ ਹੈ ਅਤੇ ਅਗਲਾ ਮੌਕਾ ਤੁਹਾਨੂੰ ਕਿੱਥੇ ਲੈ ਜਾ ਸਕਦਾ ਹੈ।", notificationsSubtitle: "ਤੁਹਾਡੀ WorkSpot ਯਾਤਰਾ ਲਈ ਲਾਭਦਾਇਕ ਯਾਦ ਦਿਹਾਣੀਆਂ ਅਤੇ ਅੱਪਡੇਟ।", helpSubtitle: "ਹੁਣ ਜੋ ਮਦਦ ਸੌਖੀ ਲੱਗੇ ਉਹ ਚੁਣੋ।", updateWithAI: "AI ਨਾਲ ਅੱਪਡੇਟ ਕਰੋ", searchOpportunities: "ਮੌਕੇ ਖੋਜੋ", whyFits: "ਇਹ ਤੁਹਾਡੇ ਲਈ ਕਿਉਂ ਢੁਕਵਾਂ ਹੈ", viewDetails: "ਵੇਰਵੇ ਵੇਖੋ", askWorkSpotAI: "WorkSpot AI ਨੂੰ ਪੁੱਛੋ", voiceMode: "ਵੌਇਸ ਮੋਡ", quickQuestions: "ਤੁਰੰਤ ਸਵਾਲ", whatHelp: "ਮੈਂ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?", markAllRead: "ਸਭ ਨੂੰ ਪੜ੍ਹਿਆ ਚਿੰਨ੍ਹਿਤ ਕਰੋ", recordAgain: "ਦੁਬਾਰਾ ਰਿਕਾਰਡ ਕਰੋ", typeInstead: "ਇਸ ਦੀ ਥਾਂ ਟਾਈਪ ਕਰੋ", previewLabel: "WORKSPOT AI · ਝਲਕ", play: "ਰਿਕਾਰਡਿੰਗ ਚਲਾਓ", pause: "ਰਿਕਾਰਡਿੰਗ ਰੋਕੋ" },
  or: { profileSubtitle: "WorkSpot ଆପଣଙ୍କ କାମ ଏବଂ ପ୍ରଗତି ବୁଝିବା ସହିତ ବଢୁଥିବା ଜୀବନ୍ତ ପ୍ରୋଫାଇଲ୍।", opportunitiesSubtitle: "ଆପଣଙ୍କ ଦକ୍ଷତା, ଅଭିଜ୍ଞତା, ସ୍ଥାନ ଏବଂ ଲକ୍ଷ୍ୟ ଆଧାରରେ।", advisorSubtitle: "ଆପଣଙ୍କ କାମ, ପ୍ରଶିକ୍ଷଣ, ସୁଯୋଗ କିମ୍ବା ସହାୟତା ବିଷୟରେ କିଛି ପଚାରନ୍ତୁ।", progressSubtitle: "ଆପଣ କଣ ସମ୍ପୂର୍ଣ୍ଣ କରିଛନ୍ତି ଏବଂ ପରବର୍ତ୍ତୀ ସୁଯୋଗ କେଉଁଠି ନେଇପାରେ ଦେଖନ୍ତୁ।", notificationsSubtitle: "ଆପଣଙ୍କ WorkSpot ଯାତ୍ରାର ଉପଯୋଗୀ ସ୍ମାରକ ଏବଂ ଅଦ୍ୟତନ।", helpSubtitle: "ଏବେ ସହଜ ଲାଗୁଥିବା ସହାୟତା ବାଛନ୍ତୁ।", updateWithAI: "AI ସହିତ ଅଦ୍ୟତନ କରନ୍ତୁ", searchOpportunities: "ସୁଯୋଗ ଖୋଜନ୍ତୁ", whyFits: "ଏହା ଆପଣଙ୍କ ପାଇଁ କାହିଁକି ଉପଯୁକ୍ତ", viewDetails: "ବିବରଣୀ ଦେଖନ୍ତୁ", askWorkSpotAI: "WorkSpot AI କୁ ପଚାରନ୍ତୁ", voiceMode: "ଭଏସ୍ ମୋଡ୍", quickQuestions: "ତୁରନ୍ତ ପ୍ରଶ୍ନ", whatHelp: "ମୁଁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?", markAllRead: "ସବୁ ପଢ଼ା ଭାବେ ଚିହ୍ନଟ କରନ୍ତୁ", recordAgain: "ପୁଣି ରେକର୍ଡ କରନ୍ତୁ", typeInstead: "ଏହା ବଦଳରେ ଟାଇପ୍ କରନ୍ତୁ", previewLabel: "WORKSPOT AI · ପ୍ରିଭ୍ୟୁ", play: "ରେକର୍ଡିଂ ଚଲାନ୍ତୁ", pause: "ରେକର୍ଡିଂ ବିରତ କରନ୍ତୁ" },
  as: { profileSubtitle: "WorkSpot-এ আপোনাৰ কাম আৰু অগ্ৰগতি বুজি লোৱাৰ লগে লগে বৃদ্ধি পোৱা জীৱন্ত প্ৰফাইল।", opportunitiesSubtitle: "আপোনাৰ দক্ষতা, অভিজ্ঞতা, স্থান আৰু লক্ষ্যৰ ওপৰত ভিত্তি কৰি।", advisorSubtitle: "আপোনাৰ কাম, প্ৰশিক্ষণ, সুযোগ বা সহায়ৰ বিষয়ে যিকোনো কথা সোধক।", progressSubtitle: "আপুনি কি সম্পূৰ্ণ কৰিছে আৰু পৰৱৰ্তী সুযোগে আপোনাক ক’লৈ লৈ যাব পাৰে চাওক।", notificationsSubtitle: "আপোনাৰ WorkSpot যাত্ৰাৰ উপযোগী সোঁৱৰণী আৰু আপডেট।", helpSubtitle: "এতিয়া সহজ অনুভৱ হোৱা সহায় বাছক।", updateWithAI: "AI-ৰে আপডেট কৰক", searchOpportunities: "সুযোগ বিচাৰক", whyFits: "এইটো আপোনাৰ বাবে কিয় উপযুক্ত", viewDetails: "বিৱৰণ চাওক", askWorkSpotAI: "WorkSpot AI-ক সোধক", voiceMode: "ভইচ মোড", quickQuestions: "দ্ৰুত প্ৰশ্ন", whatHelp: "মই কেনেকৈ সহায় কৰিব পাৰোঁ?", markAllRead: "সকলো পঢ়া বুলি চিহ্নিত কৰক", recordAgain: "পুনৰ ৰেকৰ্ড কৰক", typeInstead: "তাৰ পৰিৱৰ্তে টাইপ কৰক", previewLabel: "WORKSPOT AI · প্ৰিভিউ", play: "ৰেকৰ্ডিং চলাওক", pause: "ৰেকৰ্ডিং থমকাওক" },
  bho: { profileSubtitle: "WorkSpot रउरा के काम आ प्रगति के समझत बढ़त रहे वाला जिन्दा प्रोफाइल ह।", opportunitiesSubtitle: "रउरा के हुनर, अनुभव, जगह आ लक्ष्य के आधार पर।", advisorSubtitle: "आपन काम, ट्रेनिंग, मौका भा मदद के बारे में कुछुओ पूछीं।", progressSubtitle: "देखीं रउरा का पूरा कइले बानी आ अगिला मौका कहाँ ले जा सकेला।", notificationsSubtitle: "रउरा के WorkSpot सफर के जरूरी याद दिलावे वाला संदेश आ अपडेट।", helpSubtitle: "अभी जे मदद आसान लागे ओकरा चुनीं।", updateWithAI: "AI से अपडेट करीं", searchOpportunities: "मौका खोजीं", whyFits: "ई रउरा खातिर काहे सही बा", viewDetails: "विवरण देखीं", askWorkSpotAI: "WorkSpot AI से पूछीं", voiceMode: "आवाज मोड", quickQuestions: "जल्दी सवाल", whatHelp: "हम कइसे मदद करीं?", markAllRead: "सब पढ़ल चिन्हित करीं", recordAgain: "फेरु रिकॉर्ड करीं", typeInstead: "एकरा बदले लिखीं", previewLabel: "WORKSPOT AI · झलक", play: "रिकॉर्डिंग चलाईं", pause: "रिकॉर्डिंग रोकाईं" },
  mai: { profileSubtitle: "WorkSpot अहाँक काज आ प्रगति बुझैत बढ़ैत जीवित प्रोफाइल अछि।", opportunitiesSubtitle: "अहाँक कौशल, अनुभव, स्थान आ लक्ष्यक आधार पर।", advisorSubtitle: "अपन काज, प्रशिक्षण, अवसर वा सहायतेक बारे मे किछुओ पूछू।", progressSubtitle: "देखू अहाँ की पूरा केलहुँ आ अगिला अवसर कतय लऽ जा सकैत अछि।", notificationsSubtitle: "अहाँक WorkSpot यात्राक उपयोगी स्मरण आ अपडेट।", helpSubtitle: "एखन जे सहायता सहज लगय से चुनू।", updateWithAI: "AI सँ अपडेट करू", searchOpportunities: "अवसर खोजू", whyFits: "ई अहाँ लेल किएक उपयुक्त अछि", viewDetails: "विवरण देखू", askWorkSpotAI: "WorkSpot AI सँ पूछू", voiceMode: "आवाज मोड", quickQuestions: "जल्दी प्रश्न", whatHelp: "हम कोना सहायता करी?", markAllRead: "सभ पढ़ल चिन्हित करू", recordAgain: "फेर रिकॉर्ड करू", typeInstead: "एकर बदला मे लिखू", previewLabel: "WORKSPOT AI · झलक", play: "रिकॉर्डिंग चलाउ", pause: "रिकॉर्डिंग रोकू" },
  ur: { profileSubtitle: "WorkSpot آپ کے کام اور پیش رفت کو سمجھتے ہوئے بڑھتا ہوا زندہ پروفائل ہے۔", opportunitiesSubtitle: "آپ کی مہارت، تجربے، مقام اور مقاصد کی بنیاد پر۔", advisorSubtitle: "اپنے کام، تربیت، مواقع یا مدد کے بارے میں کچھ بھی پوچھیں۔", progressSubtitle: "دیکھیں آپ نے کیا مکمل کیا ہے اور اگلا موقع آپ کو کہاں لے جا سکتا ہے۔", notificationsSubtitle: "آپ کے WorkSpot سفر کی مفید یاد دہانیاں اور تازہ معلومات۔", helpSubtitle: "ابھی جو مدد آسان لگے اسے منتخب کریں۔", updateWithAI: "AI سے اپ ڈیٹ کریں", searchOpportunities: "مواقع تلاش کریں", whyFits: "یہ آپ کے لیے کیوں موزوں ہے", viewDetails: "تفصیلات دیکھیں", askWorkSpotAI: "WorkSpot AI سے پوچھیں", voiceMode: "وائس موڈ", quickQuestions: "فوری سوالات", whatHelp: "میں کیسے مدد کر سکتا ہوں؟", markAllRead: "سب کو پڑھا ہوا نشان زد کریں", recordAgain: "دوبارہ ریکارڈ کریں", typeInstead: "اس کے بجائے ٹائپ کریں", previewLabel: "WORKSPOT AI · پیش نظارہ", play: "ریکارڈنگ چلائیں", pause: "ریکارڈنگ روکیں" }
};

const extendedUiLabels: Record<string, Record<string, string>> = {
  en: { profileCompleteness: "PROFILE COMPLETENESS", completeDetails: "Complete two more details to get more precise recommendations.", yourInformation: "YOUR INFORMATION", everything: "Everything in one place", editable: "All sections are editable", active: "Active", milestones: "Milestones", yourJourney: "Your work journey", workPerformance: "Work performance", metrics: "Your metrics", updatedOverTime: "Updated over time", keepClose: "Keep this opportunity close", saved: "Saved", saveOpportunity: "Save opportunity", matchForYou: "Match for you", backToOpportunities: "Back to opportunities", readyNextStep: "READY FOR THE NEXT STEP?", whatYouShouldKnow: "What you should know", contactOrganization: "Contact organization" },
  bn: { profileCompleteness: "প্রোফাইল সম্পূর্ণতা", completeDetails: "আরও নির্ভুল সুপারিশ পেতে আরও দুটি তথ্য সম্পূর্ণ করুন।", yourInformation: "আপনার তথ্য", everything: "সব তথ্য এক জায়গায়", editable: "সব বিভাগ সম্পাদনাযোগ্য", active: "সক্রিয়", milestones: "মাইলস্টোন", yourJourney: "আপনার কাজের যাত্রা", workPerformance: "কাজের পারফরম্যান্স", metrics: "আপনার মেট্রিক্স", updatedOverTime: "সময়ের সঙ্গে আপডেট", keepClose: "এই সুযোগটি কাছে রাখুন", saved: "সংরক্ষিত", saveOpportunity: "সুযোগ সংরক্ষণ করুন", matchForYou: "আপনার জন্য মিল", backToOpportunities: "সুযোগগুলিতে ফিরুন", readyNextStep: "পরবর্তী ধাপের জন্য প্রস্তুত?", whatYouShouldKnow: "আপনার যা জানা উচিত", contactOrganization: "প্রতিষ্ঠানের সঙ্গে যোগাযোগ করুন" },
  hi: { profileCompleteness: "प्रोफ़ाइल पूर्णता", completeDetails: "सटीक सुझाव पाने के लिए दो और जानकारी पूरी करें।", yourInformation: "आपकी जानकारी", everything: "सब कुछ एक जगह", editable: "सभी अनुभाग संपादित किए जा सकते हैं", active: "सक्रिय", milestones: "मील के पत्थर", yourJourney: "आपकी काम की यात्रा", workPerformance: "काम का प्रदर्शन", metrics: "आपके मेट्रिक्स", updatedOverTime: "समय के साथ अपडेट", keepClose: "इस अवसर को पास रखें", saved: "सहेजा गया", saveOpportunity: "अवसर सहेजें", matchForYou: "आपके लिए मेल", backToOpportunities: "अवसरों पर वापस जाएं", readyNextStep: "अगले चरण के लिए तैयार?", whatYouShouldKnow: "आपको क्या जानना चाहिए", contactOrganization: "संगठन से संपर्क करें" },
  mr: { profileCompleteness: "प्रोफाइल पूर्णता", completeDetails: "अधिक अचूक शिफारसींसाठी आणखी दोन तपशील पूर्ण करा.", yourInformation: "तुमची माहिती", everything: "सर्व काही एका ठिकाणी", editable: "सर्व विभाग संपादित करता येतात", active: "सक्रिय", milestones: "टप्पे", yourJourney: "तुमचा कामाचा प्रवास", workPerformance: "कामगिरी", metrics: "तुमचे मेट्रिक्स", updatedOverTime: "कालानुसार अपडेट", keepClose: "ही संधी जवळ ठेवा", saved: "जतन केले", saveOpportunity: "संधी जतन करा", matchForYou: "तुमच्यासाठी जुळणारे", backToOpportunities: "संधींकडे परत जा", readyNextStep: "पुढील टप्प्यासाठी तयार?", whatYouShouldKnow: "तुम्हाला काय माहित असावे", contactOrganization: "संस्थेशी संपर्क साधा" },
  ta: { profileCompleteness: "சுயவிவர நிறைவு", completeDetails: "மேலும் துல்லியமான பரிந்துரைகளுக்கு இன்னும் இரண்டு விவரங்களை நிறைவு செய்யவும்.", yourInformation: "உங்கள் தகவல்", everything: "எல்லாம் ஒரே இடத்தில்", editable: "அனைத்து பிரிவுகளையும் திருத்தலாம்", active: "செயலில்", milestones: "மைல்கற்கள்", yourJourney: "உங்கள் வேலைப் பயணம்", workPerformance: "வேலை செயல்திறன்", metrics: "உங்கள் அளவீடுகள்", updatedOverTime: "காலப்போக்கில் புதுப்பிப்பு", keepClose: "இந்த வாய்ப்பை அருகில் வைத்திருங்கள்", saved: "சேமிக்கப்பட்டது", saveOpportunity: "வாய்ப்பைச் சேமிக்கவும்", matchForYou: "உங்களுக்கு ஏற்றது", backToOpportunities: "வாய்ப்புகளுக்குத் திரும்பு", readyNextStep: "அடுத்த படிக்குத் தயாரா?", whatYouShouldKnow: "நீங்கள் தெரிந்துகொள்ள வேண்டியது", contactOrganization: "நிறுவனத்தைத் தொடர்புகொள்ளவும்" },
  te: { profileCompleteness: "ప్రొఫైల్ పూర్తి", completeDetails: "మరింత ఖచ్చితమైన సూచనల కోసం మరో రెండు వివరాలను పూర్తి చేయండి.", yourInformation: "మీ సమాచారం", everything: "అన్నీ ఒకే చోట", editable: "అన్ని విభాగాలను సవరించవచ్చు", active: "క్రియాశీలం", milestones: "మైలురాళ్లు", yourJourney: "మీ పని ప్రయాణం", workPerformance: "పని పనితీరు", metrics: "మీ మెట్రిక్స్", updatedOverTime: "కాలానుగుణ నవీకరణ", keepClose: "ఈ అవకాశాన్ని దగ్గరగా ఉంచండి", saved: "సేవ్ చేయబడింది", saveOpportunity: "అవకాశాన్ని సేవ్ చేయండి", matchForYou: "మీకు సరిపోతుంది", backToOpportunities: "అవకాశాలకు తిరిగి వెళ్ళండి", readyNextStep: "తదుపరి దశకు సిద్ధమా?", whatYouShouldKnow: "మీరు తెలుసుకోవాల్సినవి", contactOrganization: "సంస్థను సంప్రదించండి" },
  kn: { profileCompleteness: "ಪ್ರೊಫೈಲ್ ಪೂರ್ಣತೆ", completeDetails: "ಹೆಚ್ಚು ನಿಖರವಾದ ಶಿಫಾರಸುಗಳಿಗಾಗಿ ಇನ್ನೂ ಎರಡು ವಿವರಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.", yourInformation: "ನಿಮ್ಮ ಮಾಹಿತಿ", everything: "ಎಲ್ಲವೂ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ", editable: "ಎಲ್ಲಾ ವಿಭಾಗಗಳನ್ನು ಸಂಪಾದಿಸಬಹುದು", active: "ಸಕ್ರಿಯ", milestones: "ಮೈಲಿಗಲ್ಲುಗಳು", yourJourney: "ನಿಮ್ಮ ಕೆಲಸದ ಪ್ರಯಾಣ", workPerformance: "ಕೆಲಸದ ಕಾರ್ಯಕ್ಷಮತೆ", metrics: "ನಿಮ್ಮ ಮೆಟ್ರಿಕ್‌ಗಳು", updatedOverTime: "ಕಾಲಕ್ರಮೇಣ ನವೀಕರಣ", keepClose: "ಈ ಅವಕಾಶವನ್ನು ಹತ್ತಿರದಲ್ಲಿಡಿ", saved: "ಉಳಿಸಲಾಗಿದೆ", saveOpportunity: "ಅವಕಾಶವನ್ನು ಉಳಿಸಿ", matchForYou: "ನಿಮಗೆ ಹೊಂದಿಕೆ", backToOpportunities: "ಅವಕಾಶಗಳಿಗೆ ಹಿಂತಿರುಗಿ", readyNextStep: "ಮುಂದಿನ ಹಂತಕ್ಕೆ ಸಿದ್ಧವೇ?", whatYouShouldKnow: "ನೀವು ತಿಳಿದುಕೊಳ್ಳಬೇಕಾದದ್ದು", contactOrganization: "ಸಂಸ್ಥೆಯನ್ನು ಸಂಪರ್ಕಿಸಿ" },
  ml: { profileCompleteness: "പ്രൊഫൈൽ പൂർത്തീകരണം", completeDetails: "കൂടുതൽ കൃത്യമായ ശുപാർശകൾക്കായി രണ്ട് വിശദാംശങ്ങൾ കൂടി പൂർത്തിയാക്കുക.", yourInformation: "നിങ്ങളുടെ വിവരങ്ങൾ", everything: "എല്ലാം ഒരിടത്ത്", editable: "എല്ലാ വിഭാഗങ്ങളും തിരുത്താം", active: "സജീവം", milestones: "നാഴികക്കല്ലുകൾ", yourJourney: "നിങ്ങളുടെ ജോലി യാത്ര", workPerformance: "ജോലി പ്രകടനം", metrics: "നിങ്ങളുടെ മെട്രിക്കുകൾ", updatedOverTime: "കാലക്രമേണ അപ്‌ഡേറ്റ്", keepClose: "ഈ അവസരം അടുത്ത് സൂക്ഷിക്കുക", saved: "സംരക്ഷിച്ചു", saveOpportunity: "അവസരം സംരക്ഷിക്കുക", matchForYou: "നിങ്ങൾക്ക് അനുയോജ്യം", backToOpportunities: "അവസരങ്ങളിലേക്ക് മടങ്ങുക", readyNextStep: "അടുത്ത ഘട്ടത്തിന് തയ്യാറാണോ?", whatYouShouldKnow: "നിങ്ങൾ അറിയേണ്ടത്", contactOrganization: "സ്ഥാപനവുമായി ബന്ധപ്പെടുക" },
  gu: { profileCompleteness: "પ્રોફાઇલ પૂર્ણતા", completeDetails: "વધુ ચોક્કસ ભલામણો માટે બે વધુ વિગતો પૂર્ણ કરો.", yourInformation: "તમારી માહિતી", everything: "બધું એક જ જગ્યાએ", editable: "બધા વિભાગો સંપાદિત કરી શકાય છે", active: "સક્રિય", milestones: "માઇલસ્ટોન", yourJourney: "તમારી કામની સફર", workPerformance: "કામનું પ્રદર્શન", metrics: "તમારા મેટ્રિક્સ", updatedOverTime: "સમય સાથે અપડેટ", keepClose: "આ તક નજીક રાખો", saved: "સાચવ્યું", saveOpportunity: "તક સાચવો", matchForYou: "તમારા માટે મેળ", backToOpportunities: "તકો પર પાછા જાઓ", readyNextStep: "આગલા પગલા માટે તૈયાર?", whatYouShouldKnow: "તમારે શું જાણવું જોઈએ", contactOrganization: "સંસ્થાનો સંપર્ક કરો" },
  pa: { profileCompleteness: "ਪ੍ਰੋਫ਼ਾਈਲ ਪੂਰਨਤਾ", completeDetails: "ਹੋਰ ਸਹੀ ਸੁਝਾਵਾਂ ਲਈ ਦੋ ਹੋਰ ਵੇਰਵੇ ਪੂਰੇ ਕਰੋ।", yourInformation: "ਤੁਹਾਡੀ ਜਾਣਕਾਰੀ", everything: "ਸਭ ਕੁਝ ਇੱਕ ਥਾਂ", editable: "ਸਾਰੇ ਭਾਗ ਸੰਪਾਦਿਤ ਕੀਤੇ ਜਾ ਸਕਦੇ ਹਨ", active: "ਸਰਗਰਮ", milestones: "ਮੁਕਾਮ", yourJourney: "ਤੁਹਾਡੀ ਕੰਮ ਦੀ ਯਾਤਰਾ", workPerformance: "ਕੰਮ ਦੀ ਕਾਰਗੁਜ਼ਾਰੀ", metrics: "ਤੁਹਾਡੇ ਮੈਟ੍ਰਿਕਸ", updatedOverTime: "ਸਮੇਂ ਨਾਲ ਅੱਪਡੇਟ", keepClose: "ਇਸ ਮੌਕੇ ਨੂੰ ਨੇੜੇ ਰੱਖੋ", saved: "ਸੰਭਾਲਿਆ", saveOpportunity: "ਮੌਕਾ ਸੰਭਾਲੋ", matchForYou: "ਤੁਹਾਡੇ ਲਈ ਮੇਲ", backToOpportunities: "ਮੌਕਿਆਂ ਵੱਲ ਵਾਪਸ", readyNextStep: "ਅਗਲੇ ਪੜਾਅ ਲਈ ਤਿਆਰ?", whatYouShouldKnow: "ਤੁਹਾਨੂੰ ਕੀ ਜਾਣਨਾ ਚਾਹੀਦਾ ਹੈ", contactOrganization: "ਸੰਸਥਾ ਨਾਲ ਸੰਪਰਕ ਕਰੋ" },
  or: { profileCompleteness: "ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣତା", completeDetails: "ଅଧିକ ସଠିକ ସୁପାରିଶ ପାଇଁ ଆଉ ଦୁଇଟି ବିବରଣୀ ପୂରଣ କରନ୍ତୁ।", yourInformation: "ଆପଣଙ୍କ ସୂଚନା", everything: "ସବୁ କିଛି ଗୋଟିଏ ସ୍ଥାନରେ", editable: "ସମସ୍ତ ବିଭାଗ ସମ୍ପାଦନଯୋଗ୍ୟ", active: "ସକ୍ରିୟ", milestones: "ମାଇଲଷ୍ଟୋନ୍", yourJourney: "ଆପଣଙ୍କ କାର୍ଯ୍ୟ ଯାତ୍ରା", workPerformance: "କାର୍ଯ୍ୟ ପ୍ରଦର୍ଶନ", metrics: "ଆପଣଙ୍କ ମେଟ୍ରିକ୍ସ", updatedOverTime: "ସମୟ ସହିତ ଅପଡେଟ୍", keepClose: "ଏହି ସୁଯୋଗକୁ ନିକଟରେ ରଖନ୍ତୁ", saved: "ସଞ୍ଚିତ", saveOpportunity: "ସୁଯୋଗ ସଞ୍ଚୟ କରନ୍ତୁ", matchForYou: "ଆପଣଙ୍କ ପାଇଁ ମେଳ", backToOpportunities: "ସୁଯୋଗକୁ ଫେରନ୍ତୁ", readyNextStep: "ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ ପାଇଁ ପ୍ରସ୍ତୁତ?", whatYouShouldKnow: "ଆପଣ ଯାହା ଜାଣିବା ଉଚିତ", contactOrganization: "ସଂସ୍ଥା ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ" },
  as: { profileCompleteness: "প্ৰ’ফাইল সম্পূৰ্ণতা", completeDetails: "অধিক সঠিক পৰামৰ্শৰ বাবে আৰু দুটা তথ্য পূৰ কৰক।", yourInformation: "আপোনাৰ তথ্য", everything: "সকলো একে ঠাইতে", editable: "সকলো বিভাগ সম্পাদন কৰিব পাৰি", active: "সক্ৰিয়", milestones: "মাইলষ্টোন", yourJourney: "আপোনাৰ কামৰ যাত্ৰা", workPerformance: "কামৰ প্ৰদৰ্শন", metrics: "আপোনাৰ মেট্ৰিক্স", updatedOverTime: "সময়ৰ সৈতে আপডেট", keepClose: "এই সুযোগটো ওচৰত ৰাখক", saved: "সংৰক্ষিত", saveOpportunity: "সুযোগ সংৰক্ষণ কৰক", matchForYou: "আপোনাৰ বাবে মিল", backToOpportunities: "সুযোগলৈ উভতি যাওক", readyNextStep: "পৰৱৰ্তী পদক্ষেপৰ বাবে সাজু?", whatYouShouldKnow: "আপুনি জনা উচিত", contactOrganization: "সংস্থাৰ সৈতে যোগাযোগ কৰক" },
  bho: { profileCompleteness: "प्रोफाइल पूरा", completeDetails: "अउरी सही सुझाव खातिर दू गो अउर जानकारी पूरा करीं।", yourInformation: "रउरा के जानकारी", everything: "सब कुछ एक जगह", editable: "सब सेक्शन बदलल जा सकेला", active: "सक्रिय", milestones: "पड़ाव", yourJourney: "रउरा के काम के सफर", workPerformance: "काम के प्रदर्शन", metrics: "रउरा के मेट्रिक्स", updatedOverTime: "समय के साथ अपडेट", keepClose: "ई मौका अपना लगे रखीं", saved: "सहेजल गइल", saveOpportunity: "मौका सहेजीं", matchForYou: "रउरा खातिर सही", backToOpportunities: "मौका पर वापस चलीं", readyNextStep: "अगिला कदम खातिर तैयार बानी?", whatYouShouldKnow: "रउरा का जानल चाहीं", contactOrganization: "संस्था से संपर्क करीं" },
  mai: { profileCompleteness: "प्रोफाइल पूर्णता", completeDetails: "बेसी सही सुझावक लेल दूटा आर विवरण पूरा करू।", yourInformation: "अहाँक जानकारी", everything: "सब किछु एक ठाम", editable: "सभ खण्ड सम्पादित कएल जा सकैत अछि", active: "सक्रिय", milestones: "पड़ाव", yourJourney: "अहाँक काजक यात्रा", workPerformance: "काजक प्रदर्शन", metrics: "अहाँक मेट्रिक्स", updatedOverTime: "समयक संग अपडेट", keepClose: "ई अवसर लग राखू", saved: "सहेजल", saveOpportunity: "अवसर सहेजू", matchForYou: "अहाँ लेल उपयुक्त", backToOpportunities: "अवसर पर वापस जाउ", readyNextStep: "अगिला चरण लेल तैयार?", whatYouShouldKnow: "अहाँक जेना जानब जरूरी अछि", contactOrganization: "संस्था सँ सम्पर्क करू" },
  ur: { profileCompleteness: "پروفائل کی تکمیل", completeDetails: "زیادہ درست تجاویز کے لیے دو مزید تفصیلات مکمل کریں۔", yourInformation: "آپ کی معلومات", everything: "سب کچھ ایک جگہ", editable: "تمام حصے قابلِ ترمیم ہیں", active: "فعال", milestones: "اہم مراحل", yourJourney: "آپ کا کام کا سفر", workPerformance: "کام کی کارکردگی", metrics: "آپ کے میٹرکس", updatedOverTime: "وقت کے ساتھ تازہ کاری", keepClose: "اس موقع کو قریب رکھیں", saved: "محفوظ", saveOpportunity: "موقع محفوظ کریں", matchForYou: "آپ کے لیے موزوں", backToOpportunities: "مواقع پر واپس جائیں", readyNextStep: "اگلے مرحلے کے لیے تیار؟", whatYouShouldKnow: "آپ کو کیا جاننا چاہیے", contactOrganization: "ادارے سے رابطہ کریں" }
};

const pageUiLabels: Record<string, Record<string, string>> = {
  en: { brandTagline: "Your skills. Your work. Your future.", welcomeEyebrow: "AI-POWERED LIVELIHOOD ASSISTANT", welcomeTitle: "Find the work that fits", welcomeAccent: "you.", welcomeDescription: "Tell WorkSpot what you do, what you know, and what you want to achieve. Our AI will help you discover training, jobs, and livelihood opportunities.", learnMore: "Learn more", protected: "Your information stays protected", multilingual: "Multilingual", voiceFirst: "Voice-first", listeningInLanguage: "Listening in your language", workProgressScore: "Work & Progress Score", updatedWithProgress: "Updated with your progress", simpleConversation: "A SIMPLE CONVERSATION", workStartingPoint: "Your work is the starting point.", workDescription: "WorkSpot listens, understands your experience, and helps you take the next useful step—whether that is better training, a nearby job, or support to grow your own work.", signIn: "Sign in" },
  bn: { brandTagline: "আপনার দক্ষতা। আপনার কাজ। আপনার ভবিষ্যৎ।", welcomeEyebrow: "AI-চালিত জীবিকা সহায়ক", welcomeTitle: "আপনার জন্য উপযুক্ত কাজ খুঁজুন", welcomeAccent: "আপনি।", welcomeDescription: "আপনি কী করেন, কী জানেন এবং কী অর্জন করতে চান তা WorkSpot-কে বলুন। আমাদের AI আপনাকে প্রশিক্ষণ, চাকরি ও জীবিকার সুযোগ খুঁজে পেতে সাহায্য করবে।", learnMore: "আরও জানুন", protected: "আপনার তথ্য সুরক্ষিত থাকে", multilingual: "বহুভাষিক", voiceFirst: "ভয়েস-প্রথম", listeningInLanguage: "আপনার ভাষায় শুনছে", workProgressScore: "কাজ ও অগ্রগতি স্কোর", updatedWithProgress: "আপনার অগ্রগতির সঙ্গে আপডেট", simpleConversation: "একটি সহজ কথোপকথন", workStartingPoint: "আপনার কাজই শুরুর জায়গা।", workDescription: "WorkSpot আপনার কথা শোনে, অভিজ্ঞতা বোঝে এবং পরের উপযোগী পদক্ষেপ নিতে সাহায্য করে—ভালো প্রশিক্ষণ, কাছের কাজ বা নিজের কাজ বাড়ানোর সহায়তা।", signIn: "সাইন ইন" },
  hi: { brandTagline: "आपके कौशल। आपका काम। आपका भविष्य।", welcomeEyebrow: "AI-संचालित आजीविका सहायक", welcomeTitle: "आपके लिए सही काम खोजें", welcomeAccent: "आप।", welcomeDescription: "आप क्या करते हैं, क्या जानते हैं और क्या हासिल करना चाहते हैं, WorkSpot को बताएं। हमारा AI आपको प्रशिक्षण, नौकरी और आजीविका के अवसर खोजने में मदद करेगा।", learnMore: "और जानें", protected: "आपकी जानकारी सुरक्षित रहती है", multilingual: "बहुभाषी", voiceFirst: "वॉइस-फर्स्ट", listeningInLanguage: "आपकी भाषा में सुन रहा है", workProgressScore: "कार्य और प्रगति स्कोर", updatedWithProgress: "आपकी प्रगति के साथ अपडेट", simpleConversation: "एक सरल बातचीत", workStartingPoint: "आपका काम शुरुआत है।", workDescription: "WorkSpot आपकी बात सुनता है, अनुभव समझता है और अगला उपयोगी कदम लेने में मदद करता है—बेहतर प्रशिक्षण, पास की नौकरी या अपना काम बढ़ाने में सहायता।", signIn: "साइन इन" },
  mr: { welcomeEyebrow: "AI-आधारित उपजीविका सहाय्यक", welcomeTitle: "तुमच्यासाठी योग्य काम शोधा", welcomeAccent: "तुम्ही.", welcomeDescription: "तुम्ही काय करता, काय जाणता आणि काय साध्य करू इच्छिता ते WorkSpot ला सांगा. आमचे AI प्रशिक्षण, नोकरी आणि उपजीविकेच्या संधी शोधण्यात मदत करेल.", learnMore: "अधिक जाणून घ्या", protected: "तुमची माहिती सुरक्षित आहे", multilingual: "बहुभाषिक", voiceFirst: "व्हॉइस-फर्स्ट", listeningInLanguage: "तुमच्या भाषेत ऐकत आहे", workProgressScore: "काम आणि प्रगती स्कोअर", updatedWithProgress: "तुमच्या प्रगतीनुसार अपडेट", simpleConversation: "एक साधा संवाद", workStartingPoint: "तुमचे काम ही सुरुवात आहे.", workDescription: "WorkSpot तुमचे ऐकते, अनुभव समजते आणि पुढचे उपयुक्त पाऊल घेण्यास मदत करते—चांगले प्रशिक्षण, जवळची नोकरी किंवा स्वतःचे काम वाढवण्यासाठी मदत.", signIn: "साइन इन" },
  ta: { welcomeEyebrow: "AI இயக்கும் வாழ்வாதார உதவியாளர்", welcomeTitle: "உங்களுக்கு ஏற்ற வேலையைத் தேடுங்கள்", welcomeAccent: "நீங்கள்.", welcomeDescription: "நீங்கள் என்ன செய்கிறீர்கள், என்ன தெரியும், என்ன சாதிக்க விரும்புகிறீர்கள் என்பதை WorkSpot-க்கு சொல்லுங்கள். எங்கள் AI பயிற்சி, வேலை மற்றும் வாழ்வாதார வாய்ப்புகளைக் கண்டறிய உதவும்.", learnMore: "மேலும் அறிக", protected: "உங்கள் தகவல் பாதுகாக்கப்படுகிறது", multilingual: "பல மொழிகள்", voiceFirst: "குரல் முன்னிலை", listeningInLanguage: "உங்கள் மொழியில் கேட்கிறது", workProgressScore: "வேலை மற்றும் முன்னேற்ற மதிப்பெண்", updatedWithProgress: "உங்கள் முன்னேற்றத்துடன் புதுப்பிக்கப்பட்டது", simpleConversation: "ஒரு எளிய உரையாடல்", workStartingPoint: "உங்கள் வேலைதான் தொடக்கம்.", workDescription: "WorkSpot கேட்டு, உங்கள் அனுபவத்தைப் புரிந்து, அடுத்த பயனுள்ள படியை எடுக்க உதவுகிறது—சிறந்த பயிற்சி, அருகிலுள்ள வேலை அல்லது உங்கள் வேலையை வளர்க்க உதவி.", signIn: "உள்நுழைக" },
  te: { welcomeEyebrow: "AI ఆధారిత జీవనోపాధి సహాయకుడు", welcomeTitle: "మీకు సరిపోయే పనిని కనుగొనండి", welcomeAccent: "మీరు.", welcomeDescription: "మీరు ఏమి చేస్తారు, ఏమి తెలుసు, ఏమి సాధించాలనుకుంటున్నారు WorkSpot కు చెప్పండి. మా AI శిక్షణ, ఉద్యోగాలు మరియు జీవనోపాధి అవకాశాలను కనుగొనడంలో సహాయపడుతుంది.", learnMore: "మరింత తెలుసుకోండి", protected: "మీ సమాచారం సురక్షితంగా ఉంటుంది", multilingual: "బహుభాషా", voiceFirst: "వాయిస్ ప్రాధాన్యం", listeningInLanguage: "మీ భాషలో వింటోంది", workProgressScore: "పని మరియు పురోగతి స్కోర్", updatedWithProgress: "మీ పురోగతితో నవీకరించబడింది", simpleConversation: "ఒక సరళమైన సంభాషణ", workStartingPoint: "మీ పనితోనే ప్రారంభం.", workDescription: "WorkSpot విని, మీ అనుభవాన్ని అర్థం చేసుకుని, తదుపరి ఉపయోగకరమైన అడుగు వేయడంలో సహాయపడుతుంది—మెరుగైన శిక్షణ, సమీప ఉద్యోగం లేదా మీ పనిని పెంచే మద్దతు.", signIn: "సైన్ ఇన్" },
  kn: { welcomeEyebrow: "AI ಆಧಾರಿತ ಜೀವನೋಪಾಯ ಸಹಾಯಕ", welcomeTitle: "ನಿಮಗೆ ಹೊಂದುವ ಕೆಲಸವನ್ನು ಹುಡುಕಿ", welcomeAccent: "ನೀವು.", welcomeDescription: "ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ, ಏನು ತಿಳಿದಿದ್ದೀರಿ ಮತ್ತು ಏನು ಸಾಧಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂದು WorkSpot ಗೆ ತಿಳಿಸಿ. ನಮ್ಮ AI ತರಬೇತಿ, ಉದ್ಯೋಗ ಮತ್ತು ಜೀವನೋಪಾಯದ ಅವಕಾಶಗಳನ್ನು ಹುಡುಕಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.", learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ", protected: "ನಿಮ್ಮ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ", multilingual: "ಬಹುಭಾಷಾ", voiceFirst: "ಧ್ವನಿ ಮೊದಲಿಗೆ", listeningInLanguage: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕೇಳುತ್ತಿದೆ", workProgressScore: "ಕೆಲಸ ಮತ್ತು ಪ್ರಗತಿ ಸ್ಕೋರ್", updatedWithProgress: "ನಿಮ್ಮ ಪ್ರಗತಿಯೊಂದಿಗೆ ನವೀಕರಿಸಲಾಗಿದೆ", simpleConversation: "ಸರಳ ಸಂಭಾಷಣೆ", workStartingPoint: "ನಿಮ್ಮ ಕೆಲಸವೇ ಆರಂಭ.", workDescription: "WorkSpot ಕೇಳಿ, ನಿಮ್ಮ ಅನುಭವವನ್ನು ಅರ್ಥಮಾಡಿಕೊಂಡು, ಮುಂದಿನ ಉಪಯುಕ್ತ ಹೆಜ್ಜೆ ಇಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ—ಉತ್ತಮ ತರಬೇತಿ, ಹತ್ತಿರದ ಕೆಲಸ ಅಥವಾ ನಿಮ್ಮ ಕೆಲಸ ಬೆಳೆಸಲು ಬೆಂಬಲ.", signIn: "ಸೈನ್ ಇನ್" },
  ml: { welcomeEyebrow: "AI അധിഷ്ഠിത ഉപജീവന സഹായി", welcomeTitle: "നിങ്ങൾക്ക് അനുയോജ്യമായ ജോലി കണ്ടെത്തുക", welcomeAccent: "നിങ്ങൾ.", welcomeDescription: "നിങ്ങൾ എന്താണ് ചെയ്യുന്നത്, എന്തറിയാം, എന്ത് നേടാൻ ആഗ്രഹിക്കുന്നു എന്ന് WorkSpot-നോട് പറയൂ. പരിശീലനം, ജോലി, ഉപജീവന അവസരങ്ങൾ കണ്ടെത്താൻ ഞങ്ങളുടെ AI സഹായിക്കും.", learnMore: "കൂടുതൽ അറിയുക", protected: "നിങ്ങളുടെ വിവരങ്ങൾ സുരക്ഷിതമാണ്", multilingual: "ബഹുഭാഷാ", voiceFirst: "വോയ്സ് പ്രധാനം", listeningInLanguage: "നിങ്ങളുടെ ഭാഷയിൽ കേൾക്കുന്നു", workProgressScore: "ജോലിയും പുരോഗതിയും സ്കോർ", updatedWithProgress: "നിങ്ങളുടെ പുരോഗതിയോടെ അപ്‌ഡേറ്റ് ചെയ്തു", simpleConversation: "ഒരു ലളിതമായ സംഭാഷണം", workStartingPoint: "നിങ്ങളുടെ ജോലിയാണ് തുടക്കം.", workDescription: "WorkSpot കേൾക്കുകയും അനുഭവം മനസ്സിലാക്കുകയും അടുത്ത ഉപകാരപ്രദമായ ചുവടുവെപ്പ് എടുക്കാൻ സഹായിക്കുകയും ചെയ്യുന്നു—മികച്ച പരിശീലനം, അടുത്തുള്ള ജോലി അല്ലെങ്കിൽ സ്വന്തം ജോലി വളർത്താനുള്ള പിന്തുണ.", signIn: "സൈൻ ഇൻ" },
  gu: { welcomeEyebrow: "AI સંચાલિત આજીવિકા સહાયક", welcomeTitle: "તમને યોગ્ય કામ શોધો", welcomeAccent: "તમે.", welcomeDescription: "તમે શું કરો છો, શું જાણો છો અને શું મેળવવા માંગો છો તે WorkSpot ને કહો. અમારું AI તાલીમ, નોકરી અને આજીવિકાની તકો શોધવામાં મદદ કરશે.", learnMore: "વધુ જાણો", protected: "તમારી માહિતી સુરક્ષિત રહે છે", multilingual: "બહુભાષી", voiceFirst: "વૉઇસ પ્રથમ", listeningInLanguage: "તમારી ભાષામાં સાંભળી રહ્યું છે", workProgressScore: "કામ અને પ્રગતિ સ્કોર", updatedWithProgress: "તમારી પ્રગતિ સાથે અપડેટ", simpleConversation: "એક સરળ વાતચીત", workStartingPoint: "તમારું કામ શરૂઆત છે.", workDescription: "WorkSpot સાંભળે છે, તમારો અનુભવ સમજે છે અને આગળનું ઉપયોગી પગલું લેવામાં મદદ કરે છે—વધુ સારી તાલીમ, નજીકની નોકરી અથવા પોતાનું કામ વધારવા માટે સહાય.", signIn: "સાઇન ઇન" },
  pa: { welcomeEyebrow: "AI-ਅਧਾਰਿਤ ਰੋਜ਼ੀ-ਰੋਟੀ ਸਹਾਇਕ", welcomeTitle: "ਆਪਣੇ ਲਈ ਢੁਕਵਾਂ ਕੰਮ ਲੱਭੋ", welcomeAccent: "ਤੁਸੀਂ।", welcomeDescription: "ਤੁਸੀਂ ਕੀ ਕਰਦੇ ਹੋ, ਕੀ ਜਾਣਦੇ ਹੋ ਅਤੇ ਕੀ ਹਾਸਲ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ WorkSpot ਨੂੰ ਦੱਸੋ। ਸਾਡਾ AI ਸਿਖਲਾਈ, ਨੌਕਰੀਆਂ ਅਤੇ ਰੋਜ਼ੀ-ਰੋਟੀ ਦੇ ਮੌਕੇ ਲੱਭਣ ਵਿੱਚ ਮਦਦ ਕਰੇਗਾ।", learnMore: "ਹੋਰ ਜਾਣੋ", protected: "ਤੁਹਾਡੀ ਜਾਣਕਾਰੀ ਸੁਰੱਖਿਅਤ ਰਹਿੰਦੀ ਹੈ", multilingual: "ਬਹੁਭਾਸ਼ੀ", voiceFirst: "ਵੌਇਸ ਪਹਿਲਾਂ", listeningInLanguage: "ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸੁਣ ਰਿਹਾ ਹੈ", workProgressScore: "ਕੰਮ ਅਤੇ ਤਰੱਕੀ ਸਕੋਰ", updatedWithProgress: "ਤੁਹਾਡੀ ਤਰੱਕੀ ਨਾਲ ਅੱਪਡੇਟ", simpleConversation: "ਇੱਕ ਸੌਖੀ ਗੱਲਬਾਤ", workStartingPoint: "ਤੁਹਾਡਾ ਕੰਮ ਸ਼ੁਰੂਆਤ ਹੈ।", workDescription: "WorkSpot ਸੁਣਦਾ ਹੈ, ਤੁਹਾਡਾ ਤਜਰਬਾ ਸਮਝਦਾ ਹੈ ਅਤੇ ਅਗਲਾ ਲਾਭਦਾਇਕ ਕਦਮ ਚੁੱਕਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ—ਬਿਹਤਰ ਸਿਖਲਾਈ, ਨੇੜਲੀ ਨੌਕਰੀ ਜਾਂ ਆਪਣਾ ਕੰਮ ਵਧਾਉਣ ਲਈ ਸਹਾਇਤਾ।", signIn: "ਸਾਈਨ ਇਨ" },
  or: { welcomeEyebrow: "AI ଚାଳିତ ଜୀବିକା ସହାୟକ", welcomeTitle: "ଆପଣଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ କାମ ଖୋଜନ୍ତୁ", welcomeAccent: "ଆପଣ।", welcomeDescription: "ଆପଣ କଣ କରନ୍ତି, କଣ ଜାଣନ୍ତି ଏବଂ କଣ ହାସଲ କରିବାକୁ ଚାହାନ୍ତି WorkSpot କୁ କୁହନ୍ତୁ। ଆମ AI ପ୍ରଶିକ୍ଷଣ, ଚାକିରି ଓ ଜୀବିକା ସୁଯୋଗ ଖୋଜିବାରେ ସାହାଯ୍ୟ କରିବ।", learnMore: "ଅଧିକ ଜାଣନ୍ତୁ", protected: "ଆପଣଙ୍କ ସୂଚନା ସୁରକ୍ଷିତ", multilingual: "ବହୁଭାଷୀ", voiceFirst: "ଭଏସ୍ ପ୍ରଥମ", listeningInLanguage: "ଆପଣଙ୍କ ଭାଷାରେ ଶୁଣୁଛି", workProgressScore: "କାମ ଓ ପ୍ରଗତି ସ୍କୋର", updatedWithProgress: "ଆପଣଙ୍କ ପ୍ରଗତି ସହିତ ଅପଡେଟ୍", simpleConversation: "ଏକ ସରଳ କଥାବାର୍ତ୍ତା", workStartingPoint: "ଆପଣଙ୍କ କାମ ହେଉଛି ଆରମ୍ଭ।", workDescription: "WorkSpot ଶୁଣେ, ଆପଣଙ୍କ ଅଭିଜ୍ଞତା ବୁଝେ ଏବଂ ପରବର୍ତ୍ତୀ ଉପଯୋଗୀ ପଦକ୍ଷେପ ନେବାରେ ସାହାଯ୍ୟ କରେ—ଭଲ ପ୍ରଶିକ୍ଷଣ, ନିକଟସ୍ଥ ଚାକିରି କିମ୍ବା ନିଜ କାମ ବଢ଼ାଇବାର ସହାୟତା।", signIn: "ସାଇନ୍ ଇନ୍" },
  as: { welcomeEyebrow: "AI-চালিত জীৱিকা সহায়ক", welcomeTitle: "আপোনাৰ বাবে উপযুক্ত কাম বিচাৰক", welcomeAccent: "আপুনি।", welcomeDescription: "আপুনি কি কৰে, কি জানে আৰু কি লাভ কৰিব বিচাৰে WorkSpot-ক কওক। আমাৰ AI-য়ে প্ৰশিক্ষণ, চাকৰি আৰু জীৱিকাৰ সুযোগ বিচাৰি উলিওৱাত সহায় কৰিব।", learnMore: "অধিক জানক", protected: "আপোনাৰ তথ্য সুৰক্ষিত", multilingual: "বহুভাষিক", voiceFirst: "ভইচ প্ৰথম", listeningInLanguage: "আপোনাৰ ভাষাত শুনি আছে", workProgressScore: "কাম আৰু অগ্ৰগতি স্কোৰ", updatedWithProgress: "আপোনাৰ অগ্ৰগতিৰ সৈতে আপডেট", simpleConversation: "এটা সহজ কথোপকথন", workStartingPoint: "আপোনাৰ কামেই আৰম্ভণি।", workDescription: "WorkSpot-এ শুনে, আপোনাৰ অভিজ্ঞতা বুজে আৰু পৰৱৰ্তী উপযোগী পদক্ষেপ লোৱাত সহায় কৰে—উন্নত প্ৰশিক্ষণ, ওচৰৰ চাকৰি বা নিজৰ কাম বঢ়োৱাৰ সহায়।", signIn: "ছাইন ইন" },
  bho: { welcomeEyebrow: "AI से चले वाला रोजी-रोटी सहायक", welcomeTitle: "अपना लायक काम खोजीं", welcomeAccent: "रउरा।", welcomeDescription: "रउरा का करीं, का जानीं आ का हासिल करे के चाहीं WorkSpot के बताईं। हमार AI ट्रेनिंग, नौकरी आ रोजी-रोटी के मौका खोजे में मदद करी।", learnMore: "आउर जानीं", protected: "रउरा के जानकारी सुरक्षित बा", multilingual: "बहुभाषी", voiceFirst: "वॉइस पहिले", listeningInLanguage: "रउरा के भाषा में सुनत बा", workProgressScore: "काम आ प्रगति स्कोर", updatedWithProgress: "रउरा के प्रगति से अपडेट", simpleConversation: "एक आसान बातचीत", workStartingPoint: "रउरा के कामे शुरुआत बा।", workDescription: "WorkSpot सुनेला, रउरा के अनुभव समझेला आ अगिला काम के कदम में मदद करेला—बेहतर ट्रेनिंग, नजदीकी नौकरी या अपना काम बढ़ावे के सहारा।", signIn: "साइन इन" },
  mai: { welcomeEyebrow: "AI आधारित जीविका सहायक", welcomeTitle: "अहाँक लेल उपयुक्त काज खोजू", welcomeAccent: "अहाँ।", welcomeDescription: "अहाँ की करैत छी, की जनैत छी आ की प्राप्त करऽ चाहैत छी WorkSpot केँ कहू। हमर AI प्रशिक्षण, नौकरी आ जीविकाक अवसर खोजऽ मे सहायता करत।", learnMore: "आओर जानू", protected: "अहाँक जानकारी सुरक्षित अछि", multilingual: "बहुभाषी", voiceFirst: "वॉइस प्रथम", listeningInLanguage: "अहाँक भाषामे सुनि रहल अछि", workProgressScore: "काज आ प्रगति स्कोर", updatedWithProgress: "अहाँक प्रगतिक संग अपडेट", simpleConversation: "एकटा सरल बातचीत", workStartingPoint: "अहाँक काजे शुरुआत अछि।", workDescription: "WorkSpot सुनैत अछि, अहाँक अनुभव बुझैत अछि आ आगाँक उपयोगी कदममे सहायता करैत अछि—बेसी नीक प्रशिक्षण, लगक नौकरी वा अपन काज बढ़ेबाक सहयोग।", signIn: "साइन इन" },
  ur: { welcomeEyebrow: "AI سے چلنے والا معاشی معاون", welcomeTitle: "اپنے لیے موزوں کام تلاش کریں", welcomeAccent: "آپ۔", welcomeDescription: "آپ کیا کرتے ہیں، کیا جانتے ہیں اور کیا حاصل کرنا چاہتے ہیں WorkSpot کو بتائیں۔ ہمارا AI تربیت، ملازمت اور معاشی مواقع تلاش کرنے میں مدد کرے گا۔", learnMore: "مزید جانیں", protected: "آپ کی معلومات محفوظ رہتی ہیں", multilingual: "کثیر لسانی", voiceFirst: "وائس فرسٹ", listeningInLanguage: "آپ کی زبان میں سن رہا ہے", workProgressScore: "کام اور پیش رفت اسکور", updatedWithProgress: "آپ کی پیش رفت کے ساتھ تازہ کاری", simpleConversation: "ایک سادہ گفتگو", workStartingPoint: "آپ کا کام ہی آغاز ہے۔", workDescription: "WorkSpot سنتا ہے، آپ کے تجربے کو سمجھتا ہے اور اگلا مفید قدم اٹھانے میں مدد کرتا ہے—بہتر تربیت، قریبی ملازمت یا اپنا کام بڑھانے کی مدد۔", signIn: "سائن اِن" }
};

const authUiLabels: Record<string, Record<string, string>> = {
  en: { welcomeBack: "WELCOME BACK", signInJourney: "Sign in to continue your journey.", mobileNumber: "Mobile number", enterMobile: "Enter your mobile number", sendOtp: "Send OTP", otpLabel: "Enter the 6-digit OTP", verifyContinue: "Verify and continue", changeNumber: "Change number", resendOtp: "Resend OTP", whatsapp: "Continue with WhatsApp", privacy: "Your information is used only to provide personalized work and training recommendations.", languageEyebrow: "ONE CONVERSATION, YOUR LANGUAGE", chooseLanguage: "Choose your language", languageDescription: "WorkSpot will communicate with you in your selected language.", preview: "Preview", useYourVoice: "Use your voice", writeAnswer: "Write your answer", privateAnswer: "Your answer is private. You can correct it at any time.", recording: "Recording...", cancel: "Cancel", stopRecording: "Stop Recording", question: "Question", of: "of", voicePrimary: "Voice is primary. Tap, type, or upload whenever it is easier." },
  bn: { welcomeBack: "আবার স্বাগতম", signInJourney: "আপনার যাত্রা চালিয়ে যেতে সাইন ইন করুন।", mobileNumber: "মোবাইল নম্বর", enterMobile: "আপনার মোবাইল নম্বর লিখুন", sendOtp: "OTP পাঠান", otpLabel: "৬ সংখ্যার OTP লিখুন", verifyContinue: "যাচাই করে এগিয়ে যান", changeNumber: "নম্বর বদলান", resendOtp: "আবার OTP পাঠান", whatsapp: "WhatsApp দিয়ে চালিয়ে যান", privacy: "আপনার তথ্য শুধুমাত্র ব্যক্তিগত কাজ ও প্রশিক্ষণের সুপারিশ দিতে ব্যবহার করা হয়।", languageEyebrow: "একটি কথোপকথন, আপনার ভাষায়", chooseLanguage: "আপনার ভাষা বেছে নিন", languageDescription: "আপনার নির্বাচিত ভাষায় WorkSpot আপনার সঙ্গে কথা বলবে।", preview: "প্রিভিউ", useYourVoice: "আপনার কণ্ঠ ব্যবহার করুন", writeAnswer: "আপনার উত্তর লিখুন", privateAnswer: "আপনার উত্তর ব্যক্তিগত। আপনি যেকোনো সময় সংশোধন করতে পারেন।", recording: "রেকর্ডিং চলছে...", cancel: "বাতিল", stopRecording: "রেকর্ডিং থামান", question: "প্রশ্ন", of: "এর মধ্যে", voicePrimary: "ভয়েসই প্রধান। সুবিধামতো বলুন, লিখুন বা অডিও আপলোড করুন।" },
  hi: { welcomeBack: "वापसी पर स्वागत है", signInJourney: "अपनी यात्रा जारी रखने के लिए साइन इन करें।", mobileNumber: "मोबाइल नंबर", enterMobile: "अपना मोबाइल नंबर दर्ज करें", sendOtp: "OTP भेजें", otpLabel: "6 अंकों का OTP दर्ज करें", verifyContinue: "सत्यापित करके आगे बढ़ें", changeNumber: "नंबर बदलें", resendOtp: "OTP फिर भेजें", whatsapp: "WhatsApp से जारी रखें", privacy: "आपकी जानकारी का उपयोग केवल व्यक्तिगत काम और प्रशिक्षण सुझावों के लिए किया जाता है।", languageEyebrow: "एक बातचीत, आपकी भाषा", chooseLanguage: "अपनी भाषा चुनें", languageDescription: "WorkSpot आपकी चुनी हुई भाषा में आपसे बात करेगा।", preview: "प्रीव्यू", useYourVoice: "अपनी आवाज़ का उपयोग करें", writeAnswer: "अपना उत्तर लिखें", privateAnswer: "आपका उत्तर निजी है। आप इसे कभी भी सुधार सकते हैं।", recording: "रिकॉर्डिंग...", cancel: "रद्द करें", stopRecording: "रिकॉर्डिंग रोकें", question: "प्रश्न", of: "में से", voicePrimary: "वॉइस प्राथमिक है। सुविधा के अनुसार बोलें, लिखें या ऑडियो अपलोड करें।" }
};

const additionalAuthLabels: Record<string, Record<string, string>> = {
  mr: { welcomeBack: "पुन्हा स्वागत आहे", signInJourney: "तुमचा प्रवास सुरू ठेवण्यासाठी साइन इन करा.", mobileNumber: "मोबाइल क्रमांक", enterMobile: "तुमचा मोबाइल क्रमांक टाका", sendOtp: "OTP पाठवा", otpLabel: "6 अंकी OTP टाका", verifyContinue: "पडताळून पुढे जा", changeNumber: "क्रमांक बदला", resendOtp: "OTP पुन्हा पाठवा", chooseLanguage: "तुमची भाषा निवडा", mobile: "मोबाइल" },
  ta: { welcomeBack: "மீண்டும் வரவேற்கிறோம்", signInJourney: "உங்கள் பயணத்தைத் தொடர உள்நுழையவும்.", mobileNumber: "கைபேசி எண்", enterMobile: "உங்கள் கைபேசி எண்ணை உள்ளிடவும்", sendOtp: "OTP அனுப்பவும்", otpLabel: "6 இலக்க OTP-ஐ உள்ளிடவும்", verifyContinue: "சரிபார்த்து தொடரவும்", changeNumber: "எண்ணை மாற்றவும்", resendOtp: "OTP-ஐ மீண்டும் அனுப்பவும்", chooseLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்" },
  te: { welcomeBack: "తిరిగి స్వాగతం", signInJourney: "మీ ప్రయాణాన్ని కొనసాగించడానికి సైన్ ఇన్ చేయండి.", mobileNumber: "మొబైల్ నంబర్", enterMobile: "మీ మొబైల్ నంబర్ నమోదు చేయండి", sendOtp: "OTP పంపండి", otpLabel: "6 అంకెల OTP నమోదు చేయండి", verifyContinue: "ధృవీకరించి కొనసాగండి", changeNumber: "నంబర్ మార్చండి", resendOtp: "OTP మళ్లీ పంపండి", chooseLanguage: "మీ భాషను ఎంచుకోండి" },
  kn: { welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ", signInJourney: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.", mobileNumber: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ", enterMobile: "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ", sendOtp: "OTP ಕಳುಹಿಸಿ", otpLabel: "6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ", verifyContinue: "ಪರಿಶೀಲಿಸಿ ಮುಂದುವರಿಯಿರಿ", changeNumber: "ಸಂಖ್ಯೆ ಬದಲಿಸಿ", resendOtp: "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ", chooseLanguage: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ" },
  ml: { welcomeBack: "വീണ്ടും സ്വാഗതം", signInJourney: "നിങ്ങളുടെ യാത്ര തുടരാൻ സൈൻ ഇൻ ചെയ്യുക.", mobileNumber: "മൊബൈൽ നമ്പർ", enterMobile: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക", sendOtp: "OTP അയയ്ക്കുക", otpLabel: "6 അക്ക OTP നൽകുക", verifyContinue: "പരിശോധിച്ച് തുടരുക", changeNumber: "നമ്പർ മാറ്റുക", resendOtp: "OTP വീണ്ടും അയയ്ക്കുക", chooseLanguage: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക" },
  gu: { welcomeBack: "ફરી સ્વાગત છે", signInJourney: "તમારી સફર ચાલુ રાખવા સાઇન ઇન કરો.", mobileNumber: "મોબાઇલ નંબર", enterMobile: "તમારો મોબાઇલ નંબર દાખલ કરો", sendOtp: "OTP મોકલો", otpLabel: "6 અંકનો OTP દાખલ કરો", verifyContinue: "ચકાસીને આગળ વધો", changeNumber: "નંબર બદલો", resendOtp: "OTP ફરી મોકલો", chooseLanguage: "તમારી ભાષા પસંદ કરો" },
  pa: { welcomeBack: "ਜੀ ਆਇਆਂ ਨੂੰ", signInJourney: "ਆਪਣੀ ਯਾਤਰਾ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।", mobileNumber: "ਮੋਬਾਈਲ ਨੰਬਰ", enterMobile: "ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ", sendOtp: "OTP ਭੇਜੋ", otpLabel: "6 ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ", verifyContinue: "ਜਾਂਚ ਕਰਕੇ ਅੱਗੇ ਵਧੋ", changeNumber: "ਨੰਬਰ ਬਦਲੋ", resendOtp: "OTP ਦੁਬਾਰਾ ਭੇਜੋ", chooseLanguage: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ" },
  or: { welcomeBack: "ପୁଣି ସ୍ୱାଗତ", signInJourney: "ଆପଣଙ୍କ ଯାତ୍ରା ଜାରି ରଖିବାକୁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ।", mobileNumber: "ମୋବାଇଲ୍ ନମ୍ବର", enterMobile: "ଆପଣଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଲେଖନ୍ତୁ", sendOtp: "OTP ପଠାନ୍ତୁ", otpLabel: "6 ଅଙ୍କର OTP ଲେଖନ୍ତୁ", verifyContinue: "ଯାଞ୍ଚ କରି ଆଗକୁ ଯାଆନ୍ତୁ", changeNumber: "ନମ୍ବର ବଦଳାନ୍ତୁ", resendOtp: "OTP ପୁଣି ପଠାନ୍ତୁ", chooseLanguage: "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ" },
  as: { welcomeBack: "পুনৰ স্বাগতম", signInJourney: "আপোনাৰ যাত্ৰা অব্যাহত ৰাখিবলৈ ছাইন ইন কৰক।", mobileNumber: "ম’বাইল নম্বৰ", enterMobile: "আপোনাৰ ম’বাইল নম্বৰ দিয়ক", sendOtp: "OTP পঠিয়াওক", otpLabel: "6 সংখ্যাৰ OTP দিয়ক", verifyContinue: "পৰীক্ষা কৰি আগবাঢ়ক", changeNumber: "নম্বৰ সলনি কৰক", resendOtp: "OTP পুনৰ পঠিয়াওক", chooseLanguage: "আপোনাৰ ভাষা বাছক" },
  bho: { welcomeBack: "फेरु स्वागत बा", signInJourney: "अपना सफर जारी रखे खातिर साइन इन करीं।", mobileNumber: "मोबाइल नंबर", enterMobile: "अपना मोबाइल नंबर डालीं", sendOtp: "OTP भेजीं", otpLabel: "6 अंक के OTP डालीं", verifyContinue: "जाँच क के आगे बढ़ीं", changeNumber: "नंबर बदलीं", resendOtp: "OTP फेर भेजीं", chooseLanguage: "अपना भाषा चुनीं" },
  mai: { welcomeBack: "फेर स्वागत अछि", signInJourney: "अपन यात्रा जारी रखबाक लेल साइन इन करू।", mobileNumber: "मोबाइल नंबर", enterMobile: "अपन मोबाइल नंबर लिखू", sendOtp: "OTP पठाउ", otpLabel: "6 अंकक OTP लिखू", verifyContinue: "जाँच कऽ आगाँ बढ़ू", changeNumber: "नंबर बदलू", resendOtp: "OTP फेर पठाउ", chooseLanguage: "अपन भाषा चुनू" },
  ur: { welcomeBack: "خوش آمدید", signInJourney: "اپنا سفر جاری رکھنے کے لیے سائن اِن کریں۔", mobileNumber: "موبائل نمبر", enterMobile: "اپنا موبائل نمبر درج کریں", sendOtp: "OTP بھیجیں", otpLabel: "6 ہندسوں کا OTP درج کریں", verifyContinue: "تصدیق کر کے جاری رکھیں", changeNumber: "نمبر تبدیل کریں", resendOtp: "OTP دوبارہ بھیجیں", chooseLanguage: "اپنی زبان منتخب کریں" }
};

const appUiLabels: Record<string, Record<string, string>> = {
  en: { homeEyebrow: "GOOD MORNING, ANITA", homeTitle: "What would you like to work on today?", homeDescription: "WorkSpot is here to help you find the next useful step in your work journey.", askAI: "Ask WorkSpot AI", exploreOpportunities: "Explore opportunities", snapshot: "YOUR SNAPSHOT", keepMoving: "Keep moving forward", viewProgress: "View progress", score: "Work & Progress Score", thisMonth: "+4 this month", profileCompleteness: "Profile completeness", detailsLeft: "2 details left", savedOpportunities: "Saved opportunities", closingSoon: "1 closing soon", recommendedNext: "RECOMMENDED NEXT STEP", continueTraining: "Continue your training journey", trainingDescription: "You enrolled in Bamboo Craft Training last week. Log your first session to keep your profile up to date.", updateProgress: "Update progress", matchedForYou: "MATCHED FOR YOU", viewOpportunity: "View opportunity", matchesExperience: "Matches your existing experience", all: "All", jobs: "Jobs", training: "Training", selfEmployment: "Self-employment", schemes: "Schemes", match: "match", apply: "Apply", explore: "Explore", conversationPartner: "YOUR CONVERSATION PARTNER", respondsIn: "Responds in", voiceMode: "Voice mode", you: "You", listen: "Listen", askPlaceholder: "Ask a question in your language...", quickQuestions: "Quick questions", whatHelp: "What can I help with?", trainingGoingWell: "Training going well", checkOpportunity: "Check my opportunity", needFinancial: "Need financial support", needToolkit: "Need tool-kit support", needMarket: "Need market support", updateProfile: "Update my profile", talkHuman: "Talk to a human officer", voiceAvailable: "Voice is always available.", sendOnly: "Your answer is only sent when you choose to send it.", completed: "completed", profileCreated: "Profile Created", trainingRecommended: "Training Recommended", trainingStarted: "Training Started", trainingCompleted: "Training Completed", inProgress: "In progress", workStarted: "Work Started", upcoming: "Upcoming", incomeProgress: "Income / Profit Progress", tracking: "Tracking", workActivity: "Work activity", currentStatus: "Current status", skillProficiency: "Skill proficiency", developingWell: "Developing well", trainingCompletion: "Training completion", scoreDescription: "Your score changes as WorkSpot receives new verified progress information.", sinceMonth: "+14 since month 1", month1: "Month 1", month2: "Month 2", month3: "Month 3" },
  bn: { homeEyebrow: "শুভ সকাল, অনিতা", homeTitle: "আজ আপনি কোন কাজটি করতে চান?", homeDescription: "আপনার কাজের যাত্রায় পরের উপযোগী পদক্ষেপ খুঁজে পেতে WorkSpot আপনাকে সাহায্য করবে।", askAI: "WorkSpot AI-কে জিজ্ঞাসা করুন", exploreOpportunities: "সুযোগ দেখুন", snapshot: "আপনার সংক্ষিপ্ত চিত্র", keepMoving: "এগিয়ে চলুন", viewProgress: "অগ্রগতি দেখুন", score: "কাজ ও অগ্রগতি স্কোর", thisMonth: "এই মাসে +৪", profileCompleteness: "প্রোফাইল সম্পূর্ণতা", detailsLeft: "আরও ২টি তথ্য বাকি", savedOpportunities: "সংরক্ষিত সুযোগ", closingSoon: "১টি শীঘ্রই বন্ধ হবে", recommendedNext: "পরবর্তী সুপারিশকৃত ধাপ", continueTraining: "আপনার প্রশিক্ষণ যাত্রা চালিয়ে যান", trainingDescription: "আপনি গত সপ্তাহে বাঁশের কারুশিল্প প্রশিক্ষণে ভর্তি হয়েছেন। প্রোফাইল আপডেট রাখতে প্রথম সেশনটি নথিভুক্ত করুন।", updateProgress: "অগ্রগতি আপডেট করুন", matchedForYou: "আপনার জন্য মিলেছে", viewOpportunity: "সুযোগ দেখুন", matchesExperience: "আপনার বর্তমান অভিজ্ঞতার সঙ্গে মেলে", all: "সব", jobs: "চাকরি", training: "প্রশিক্ষণ", selfEmployment: "স্বনিয়োজিত কাজ", schemes: "স্কিম", match: "মিল", apply: "আবেদন করুন", explore: "দেখুন", conversationPartner: "আপনার কথোপকথনের সঙ্গী", respondsIn: "উত্তর দিচ্ছে", voiceMode: "ভয়েস মোড", you: "আপনি", listen: "শুনুন", askPlaceholder: "আপনার ভাষায় প্রশ্ন করুন...", quickQuestions: "দ্রুত প্রশ্ন", whatHelp: "আমি কীভাবে সাহায্য করতে পারি?", trainingGoingWell: "প্রশিক্ষণ ভালো চলছে", checkOpportunity: "আমার সুযোগ দেখুন", needFinancial: "আর্থিক সহায়তা দরকার", needToolkit: "টুল-কিট সহায়তা দরকার", needMarket: "বাজার সহায়তা দরকার", updateProfile: "আমার প্রোফাইল আপডেট করুন", talkHuman: "একজন কর্মকর্তার সঙ্গে কথা বলুন", voiceAvailable: "ভয়েস সবসময় পাওয়া যায়।", sendOnly: "আপনি পাঠালে তবেই আপনার উত্তর পাঠানো হবে।", completed: "সম্পন্ন", profileCreated: "প্রোফাইল তৈরি", trainingRecommended: "প্রশিক্ষণ সুপারিশ করা হয়েছে", trainingStarted: "প্রশিক্ষণ শুরু হয়েছে", trainingCompleted: "প্রশিক্ষণ সম্পন্ন", inProgress: "চলমান", workStarted: "কাজ শুরু", upcoming: "আসন্ন", incomeProgress: "আয় / লাভের অগ্রগতি", tracking: "ট্র্যাকিং", workActivity: "কাজের কার্যকলাপ", currentStatus: "বর্তমান অবস্থা", skillProficiency: "দক্ষতার পারদর্শিতা", developingWell: "ভালোভাবে উন্নতি হচ্ছে", trainingCompletion: "প্রশিক্ষণ সম্পূর্ণতা", scoreDescription: "WorkSpot নতুন যাচাই করা অগ্রগতি পেলে আপনার স্কোর বদলায়।", sinceMonth: "প্রথম মাস থেকে +১৪", month1: "মাস ১", month2: "মাস ২", month3: "মাস ৩" },
  hi: { homeEyebrow: "सुप्रभात, अनीता", homeTitle: "आज आप किस काम पर ध्यान देना चाहेंगी?", homeDescription: "WorkSpot आपकी काम की यात्रा में अगला उपयोगी कदम खोजने में मदद करेगा।", askAI: "WorkSpot AI से पूछें", exploreOpportunities: "अवसर देखें", snapshot: "आपकी झलक", keepMoving: "आगे बढ़ते रहें", viewProgress: "प्रगति देखें", score: "कार्य और प्रगति स्कोर", thisMonth: "इस महीने +4", profileCompleteness: "प्रोफ़ाइल पूर्णता", detailsLeft: "2 जानकारी बाकी", savedOpportunities: "सहेजे गए अवसर", closingSoon: "1 जल्द बंद होगा", recommendedNext: "सुझाया गया अगला कदम", continueTraining: "अपनी प्रशिक्षण यात्रा जारी रखें", trainingDescription: "आपने पिछले सप्ताह बांस शिल्प प्रशिक्षण में दाखिला लिया। प्रोफ़ाइल अपडेट रखने के लिए अपना पहला सत्र दर्ज करें।", updateProgress: "प्रगति अपडेट करें", matchedForYou: "आपके लिए मेल", viewOpportunity: "अवसर देखें", matchesExperience: "आपके मौजूदा अनुभव से मेल खाता है", all: "सभी", jobs: "नौकरियां", training: "प्रशिक्षण", selfEmployment: "स्वरोज़गार", schemes: "योजनाएं", match: "मेल", apply: "आवेदन करें", explore: "देखें", conversationPartner: "आपका बातचीत साथी", respondsIn: "उत्तर दे रहा है", voiceMode: "वॉइस मोड", you: "आप", listen: "सुनें", askPlaceholder: "अपनी भाषा में प्रश्न पूछें...", quickQuestions: "त्वरित प्रश्न", whatHelp: "मैं कैसे मदद कर सकता हूं?", trainingGoingWell: "प्रशिक्षण अच्छा चल रहा है", checkOpportunity: "मेरा अवसर देखें", needFinancial: "वित्तीय सहायता चाहिए", needToolkit: "टूल-किट सहायता चाहिए", needMarket: "बाज़ार सहायता चाहिए", updateProfile: "मेरी प्रोफ़ाइल अपडेट करें", talkHuman: "मानव अधिकारी से बात करें", voiceAvailable: "वॉइस हमेशा उपलब्ध है।", sendOnly: "आपके भेजने पर ही उत्तर भेजा जाएगा।", completed: "पूरा", profileCreated: "प्रोफ़ाइल बनाई गई", trainingRecommended: "प्रशिक्षण सुझाया गया", trainingStarted: "प्रशिक्षण शुरू", trainingCompleted: "प्रशिक्षण पूरा", inProgress: "जारी", workStarted: "काम शुरू", upcoming: "आगामी", incomeProgress: "आय / लाभ की प्रगति", tracking: "ट्रैकिंग", workActivity: "काम की गतिविधि", currentStatus: "वर्तमान स्थिति", skillProficiency: "कौशल दक्षता", developingWell: "अच्छी प्रगति", trainingCompletion: "प्रशिक्षण पूर्णता", scoreDescription: "WorkSpot को नई सत्यापित प्रगति मिलने पर आपका स्कोर बदलता है।", sinceMonth: "पहले महीने से +14", month1: "महीना 1", month2: "महीना 2", month3: "महीना 3" }
};

export function getLocaleCopy(language: string, fallback: Record<string, any>) {
  const locale = locales[getLanguageConfig(language).code] ?? en;
  const code = getLanguageConfig(language).code;
  const ui = { ...uiLabels[code] ?? uiLabels.en, ...extendedUiLabels[code], ...pageUiLabels[code], ...authUiLabels.en, ...authUiLabels[code], ...additionalAuthLabels[code], ...appUiLabels.en, ...appUiLabels[code] };
  return {
    ...fallback,
    nav: [locale.navigation.home, locale.navigation.profile, locale.navigation.opportunities, locale.navigation.ai, locale.navigation.progress, locale.navigation.notifications],
    continue: locale.common.continue,
    listen: locale.common.listen,
    send: locale.common.send,
    profile: locale.navigation.profile,
    opportunities: locale.navigation.opportunities,
    advisor: locale.navigation.ai,
    progress: locale.navigation.progress,
    help: locale.navigation.help,
    type: fallback.type,
    speak: locale.voice.speakIn,
    ui
  };
}
